//
//  GalleryForColoredPicsConstants.h
//  KidsPaint
//
//  Created by Roman Smirnov on 14.05.12.
//  Copyright (c) 2012 Aplica. All rights reserved.
//

#ifndef KidsPaint_GalleryForColoredPicsConstants_h
#define KidsPaint_GalleryForColoredPicsConstants_h

typedef int galleryType;

// тип галереи
enum galleryType
{
    GALLERY_TYPE_FLAT,                                  // 0 - все листы на одном уровне
    GALLERY_TYPE_SIDES_SHEETS_FAR                       // 1 - боковые листы утоплены вглубь экрана
};


typedef int sheetColoredTypeID;

enum sheetColoredTypeID{
    SHEET_COLORED_TYPE_LEFT,
    SHEET_COLORED_TYPE_RIGHT    
};

typedef int sheetColoredState;

enum sheetColoredState{
    SHEET_COLORED_STATE_SHOWING_PICS,
    SHEET_COLORED_STATE_STABILIZING,
    SHEET_COLORED_STATE_SCALING_TO_PAINTING_AREA,
    SHEET_COLORED_STATE_HIDING,
    SHEET_COLORED_STATE_HIDDEN,
    SHEET_COLORED_STATE_UNSCALING_FROM_PAINTING_AREA
};

typedef int galleryColoredState;

enum galleryColoredState{
    GALLERY_COLORED_STATE_SHOWING_PICS,
    GALLERY_COLORED_STATE_STABILIZING,  
    GALLERY_COLORED_STATE_SCALING_TO_PAINTING_AREA,
    GALLERY_COLORED_STATE_HIDDEN,
    GALLERY_COLORED_STATE_UNSCALING_FROM_PAINTING_AREA
};


#define COLOR_HACK_CONSTANT (25.0) //расстояние между двумя соседними парами листов

#define COLORED_TRANSLATION_SPEED_FACTOR (0.1) //с какой скоростью двигаем пальцем листы

#define COLORED_SHEET_NEIGHBOORS_COUNT_LEFT (2) //для скольких листов слева от активного подгружаем текстуры
#define COLORED_SHEET_NEIGHBOORS_COUNT_RIGHT (4) //для скольких листов справа от активного подгружаем текстуры

#define COLORED_RIGHT_SHEET_START_ROTATION (-20)
#define COLORED_LEFT_SHEET_START_ROTATION (-COLORED_RIGHT_SHEET_START_ROTATION)

#define COLORED_RIGHT_LIMIT_ROTATION (-20)
#define COLORED_LEFT_LIMIT_ROTATION (-COLORED_RIGHT_LIMIT_ROTATION)

#define COLORED_SHEET_SCALE_X (0.8)
#define COLORED_SHEET_SCALE_Y (0.8)
#define COLORED_SHEET_SCALE_Z (1.0)

//#define COLORED_TRANSLATION_ZONE_1_LEFT_BORDER_FOR_LEFT_SHEET (-0.55)
#define COLORED_TRANSLATION_ZONE_1_LEFT_BORDER_FOR_LEFT_SHEET (-3.0)
//#define COLORED_TRANSLATION_ZONE_1_RIGHT_BORDER_FOR_LEFT_SHEET (3.45)
#define COLORED_TRANSLATION_ZONE_1_RIGHT_BORDER_FOR_LEFT_SHEET (3.0)
#define COLORED_TRANSLATION_ZONE_1_LENGHT_FOR_LEFT_SHEET (COLORED_TRANSLATION_ZONE_1_RIGHT_BORDER_FOR_LEFT_SHEET - COLORED_TRANSLATION_ZONE_1_LEFT_BORDER_FOR_LEFT_SHEET)

#define COLORED_TRANSLATION_ZONE_1_LEFT_BORDER_FOR_RIGHT_SHEET (-30.0)
//#define COLORED_TRANSLATION_ZONE_1_LEFT_BORDER_FOR_RIGHT_SHEET (-3.0)
#define COLORED_TRANSLATION_ZONE_1_RIGHT_BORDER_FOR_RIGHT_SHEET (30.0)
//#define COLORED_TRANSLATION_ZONE_1_RIGHT_BORDER_FOR_RIGHT_SHEET (3.0)
#define COLORED_TRANSLATION_ZONE_1_LENGHT_FOR_RIGHT_SHEET (COLORED_TRANSLATION_ZONE_1_RIGHT_BORDER_FOR_RIGHT_SHEET - COLORED_TRANSLATION_ZONE_1_LEFT_BORDER_FOR_RIGHT_SHEET)


// параметры анимации "докрутки" страниц после убирания пальца с экрана
#define COLORED_STABILIZATION_TIME (0.2) // время, за которое после отпускания пальца анимация останавливается
#define COLORED_STABILIZATION_ACCELERATION (1.0) // ускорение сталбилизации


//параметры анимации превращения выбранной страницы в раскрашиваемую
#define COLORED_SCALING_TO_PAINTING_PAGE_DURATION (0.8)
#define COLORED_SCALING_TO_GALLERY_PAGE_DURATION (0.8)

#define COLORED_SCALING_TO_PAINTING_PAGE_END_TRANSLATION_X (6.0)
#define COLORED_SCALING_TO_PAINTING_PAGE_END_TRANSLATION_Y (21.1)
#define COLORED_SCALING_TO_PAINTING_PAGE_END_TRANSLATION_Z (4.0)

#define COLORED_SCALING_TO_PAINTING_PAGE_END_ROTATION_X (0.0)
#define COLORED_SCALING_TO_PAINTING_PAGE_END_ROTATION_Y (180.0)
#define COLORED_SCALING_TO_PAINTING_PAGE_END_ROTATION_Z (0.0)

#define COLORED_SCALING_TO_PAINTING_PAGE_END_SCALE_X (2.145)
#define COLORED_SCALING_TO_PAINTING_PAGE_END_SCALE_Y (2.145)
#define COLORED_SCALING_TO_PAINTING_PAGE_END_SCALE_Z (1.0)

#endif
